### ISSUE TITLE
Update to support HACS

### ISSUE THREAD

**Issue by va-lemon** [vinteo/hass-neeo#4]
Add support for Home Assistant Community Store as I believe development of the Custom Updater has stopped. 

https://custom-components.github.io/hacs/

**Comment by vinteo** [comment]
@va-lemon thanks for creating this issue.

I don't think it will be difficult to do so I will probably do it when I have some time. 

But with NEEO basically out of development now (and probably stop working after 1.5 years?) and this component seeming working without any reported issues, I doubt there will be any actual updates to this component in the future.

**Comment by va-lemon** [comment]
I thought about NEEO reaching end-of-life just a few moments after submitting this issue. As it is, this integration works great and I wouldn't expect any further changes other than those necessitated by Home Assistant. You can close this issue. Thanks for creating this!

**Comment by vinteo** [comment]
@va-lemon added HACS support :)

**Comment by va-lemon** [comment]
Works great! Thx!
